# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 754c429d9499c0425e5ee2a21c1f45f9e4b6d5ca4fabd7a8856af0f5f7a024d19d5d78c4965a11e6e1ea32e57a64427f13d18ccf4558532f4ce1a81298972c86

test:
  secret_key_base: 0eec107ad6c94d2516e68e43951d45181647f7bd8683b48903820532794dbece7772e69089af4fa5751e0b929bd70376de128638698e3bb798223de4446a20d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
